### ISSUE TITLE
VGG_Flowers seems missing

### ISSUE THREAD

**Issue by rishi2002** [joey-wang123/SDML#1]
The dataset on google drive does not have vgg_flowers, which results in an error while execution. The logo dataset also seems missing. 
![error](https://user-images.githubusercontent.com/74735335/222364945-846dae9c-084c-479e-a415-6de3fc4ef91f.png)

**Comment by joey-wang123** [comment]
Hello,

             Thanks for your interest! VGGflower dataset is not used here, so you can skip this dataset.

**Comment by rishi2002** [comment]
Thank You!
